// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class Book;
@class BookBuilder;
@class BookChapterReq;
@class BookChapterReqBuilder;
@class BookChapterRes;
@class BookChapterResBuilder;
@class BookChapterSourceReq;
@class BookChapterSourceReqBuilder;
@class BookChapterSourceRes;
@class BookChapterSourceResBuilder;
@class BookNo;
@class BookNoBuilder;
@class BookRelateReq;
@class BookRelateReqBuilder;
@class BookRelateRes;
@class BookRelateResBuilder;
@class BookSearchReq;
@class BookSearchReqBuilder;
@class BookSearchRes;
@class BookSearchResBuilder;
@class BookStoreReq;
@class BookStoreReqBuilder;
@class BookStoreRes;
@class BookStoreResBuilder;
@class Chapter;
@class ChapterBuilder;
@class Device;
@class DeviceBuilder;
@class DeviceSize;
@class DeviceSizeBuilder;
@class DeviceUdId;
@class DeviceUdIdBuilder;
@class FirstBookReq;
@class FirstBookReqBuilder;
@class FirstBookRes;
@class FirstBookResBuilder;
@class FirstBookTypeReq;
@class FirstBookTypeReqBuilder;
@class FirstBookTypeRes;
@class FirstBookTypeResBuilder;
@class FtBookApiReq;
@class FtBookApiReqBuilder;
@class FtBookApiRes;
@class FtBookApiResBuilder;
@class Source;
@class SourceBuilder;
@class SourceLastChapter;
@class SourceLastChapterBuilder;
@class TopicChart;
@class TopicChartBookReq;
@class TopicChartBookReqBuilder;
@class TopicChartBookRes;
@class TopicChartBookResBuilder;
@class TopicChartBuilder;
@class TopicChartReq;
@class TopicChartReqBuilder;
@class TopicChartRes;
@class TopicChartResBuilder;
@class TopicHomeReq;
@class TopicHomeReqBuilder;
@class TopicHomeRes;
@class TopicHomeResBuilder;
@class UserBook;
@class UserBookBuilder;
@class UserBookStoreOperateReq;
@class UserBookStoreOperateReqBuilder;
@class UserBookStoreReq;
@class UserBookStoreReqBuilder;
@class UserBookStoreRes;
@class UserBookStoreResBuilder;


typedef NS_ENUM(SInt32, BookState) {
  BookStateStateUnknown = 0,
  BookStateStateWriting = 1,
  BookStateStateFinished = 2,
  BookStateStatePause = 3,
};

BOOL BookStateIsValidValue(BookState value);
NSString *NSStringFromBookState(BookState value);

typedef NS_ENUM(SInt32, SourceState) {
  SourceStateSourcestateUnknown = 0,
  SourceStateSourcestateWorking = 1,
  SourceStateSourcestateStop = 2,
  SourceStateSourcestatePause = 3,
};

BOOL SourceStateIsValidValue(SourceState value);
NSString *NSStringFromSourceState(SourceState value);

typedef NS_ENUM(SInt32, CopyrightState) {
  CopyrightStateCopyrightstateHave = 0,
  CopyrightStateCopyrightstateNo = 1,
};

BOOL CopyrightStateIsValidValue(CopyrightState value);
NSString *NSStringFromCopyrightState(CopyrightState value);

typedef NS_ENUM(SInt32, GenderType) {
  GenderTypeGenderUnknown = 0,
  GenderTypeGenderMale = 1,
  GenderTypeGenderFemale = 2,
  GenderTypeGenderOther = 3,
};

BOOL GenderTypeIsValidValue(GenderType value);
NSString *NSStringFromGenderType(GenderType value);

typedef NS_ENUM(SInt32, ErrCode) {
  ErrCodeErrNone = 0,
  ErrCodeErrCannotdecode = 1,
  ErrCodeErrCannotdecodein = 3,
  ErrCodeErrCannotadddelmodify = 5,
  ErrCodeErrBooknotexist = 7,
  ErrCodeErrUnknow = 9999,
};

BOOL ErrCodeIsValidValue(ErrCode value);
NSString *NSStringFromErrCode(ErrCode value);

typedef NS_ENUM(SInt32, UserBookStoreOperateType) {
  UserBookStoreOperateTypeOperateAdd = 0,
  UserBookStoreOperateTypeOperateDel = 1,
  UserBookStoreOperateTypeOperateTop = 2,
  UserBookStoreOperateTypeOperateUntop = 3,
};

BOOL UserBookStoreOperateTypeIsValidValue(UserBookStoreOperateType value);
NSString *NSStringFromUserBookStoreOperateType(UserBookStoreOperateType value);

typedef NS_ENUM(SInt32, DeviceDeviceType) {
  DeviceDeviceTypeDeviceUnknown = 0,
  DeviceDeviceTypeDevicePhone = 1,
  DeviceDeviceTypeDeviceTablet = 2,
  DeviceDeviceTypeDeviceWear = 3,
  DeviceDeviceTypeDevicePc = 4,
  DeviceDeviceTypeDeviceOther = 99,
};

BOOL DeviceDeviceTypeIsValidValue(DeviceDeviceType value);
NSString *NSStringFromDeviceDeviceType(DeviceDeviceType value);

typedef NS_ENUM(SInt32, DeviceOsType) {
  DeviceOsTypeWin = 0,
  DeviceOsTypeAndroid = 1,
  DeviceOsTypeIos = 2,
  DeviceOsTypeWp = 3,
};

BOOL DeviceOsTypeIsValidValue(DeviceOsType value);
NSString *NSStringFromDeviceOsType(DeviceOsType value);


@interface FtbookRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Book_book_id @"bookId"
#define Book_name @"name"
#define Book_book_type @"bookType"
#define Book_book_length @"bookLength"
#define Book_author @"author"
#define Book_key_word @"keyWord"
#define Book_abstract @"abstract"
#define Book_clicked @"clicked"
#define Book_pic @"pic"
#define Book_book_state @"bookState"
#define Book_last_chapter @"lastChapter"
@interface Book : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasName_:1;
  BOOL hasAuthor_:1;
  BOOL hasAbstract_:1;
  BOOL hasPic_:1;
  BOOL hasLastChapter_:1;
  BOOL hasBookId_:1;
  BOOL hasBookLength_:1;
  BOOL hasClicked_:1;
  BOOL hasBookState_:1;
  NSString* name;
  NSString* author;
  NSString* abstract;
  NSString* pic;
  Chapter* lastChapter;
  UInt32 bookId;
  UInt32 bookLength;
  UInt32 clicked;
  BookState bookState;
  NSMutableArray * bookTypeArray;
  NSMutableArray * keyWordArray;
}
- (BOOL) hasBookId;
- (BOOL) hasName;
- (BOOL) hasBookLength;
- (BOOL) hasAuthor;
- (BOOL) hasAbstract;
- (BOOL) hasClicked;
- (BOOL) hasPic;
- (BOOL) hasBookState;
- (BOOL) hasLastChapter;
@property (readonly) UInt32 bookId;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSArray * bookType;
@property (readonly) UInt32 bookLength;
@property (readonly, strong) NSString* author;
@property (readonly, strong) NSArray * keyWord;
@property (readonly, strong) NSString* abstract;
@property (readonly) UInt32 clicked;
@property (readonly, strong) NSString* pic;
@property (readonly) BookState bookState;
@property (readonly, strong) Chapter* lastChapter;
- (NSString*)bookTypeAtIndex:(NSUInteger)index;
- (NSString*)keyWordAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BookBuilder*) builder;
+ (BookBuilder*) builder;
+ (BookBuilder*) builderWithPrototype:(Book*) prototype;
- (BookBuilder*) toBuilder;

+ (Book*) parseFromData:(NSData*) data;
+ (Book*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Book*) parseFromInputStream:(NSInputStream*) input;
+ (Book*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Book*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Book*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BookBuilder : PBGeneratedMessageBuilder {
@private
  Book* resultBook;
}

- (Book*) defaultInstance;

- (BookBuilder*) clear;
- (BookBuilder*) clone;

- (Book*) build;
- (Book*) buildPartial;

- (BookBuilder*) mergeFrom:(Book*) other;
- (BookBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BookBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBookId;
- (UInt32) bookId;
- (BookBuilder*) setBookId:(UInt32) value;
- (BookBuilder*) clearBookId;

- (BOOL) hasName;
- (NSString*) name;
- (BookBuilder*) setName:(NSString*) value;
- (BookBuilder*) clearName;

- (NSMutableArray *)bookType;
- (NSString*)bookTypeAtIndex:(NSUInteger)index;
- (BookBuilder *)addBookType:(NSString*)value;
- (BookBuilder *)setBookTypeArray:(NSArray *)array;
- (BookBuilder *)clearBookType;

- (BOOL) hasBookLength;
- (UInt32) bookLength;
- (BookBuilder*) setBookLength:(UInt32) value;
- (BookBuilder*) clearBookLength;

- (BOOL) hasAuthor;
- (NSString*) author;
- (BookBuilder*) setAuthor:(NSString*) value;
- (BookBuilder*) clearAuthor;

- (NSMutableArray *)keyWord;
- (NSString*)keyWordAtIndex:(NSUInteger)index;
- (BookBuilder *)addKeyWord:(NSString*)value;
- (BookBuilder *)setKeyWordArray:(NSArray *)array;
- (BookBuilder *)clearKeyWord;

- (BOOL) hasAbstract;
- (NSString*) abstract;
- (BookBuilder*) setAbstract:(NSString*) value;
- (BookBuilder*) clearAbstract;

- (BOOL) hasClicked;
- (UInt32) clicked;
- (BookBuilder*) setClicked:(UInt32) value;
- (BookBuilder*) clearClicked;

- (BOOL) hasPic;
- (NSString*) pic;
- (BookBuilder*) setPic:(NSString*) value;
- (BookBuilder*) clearPic;

- (BOOL) hasBookState;
- (BookState) bookState;
- (BookBuilder*) setBookState:(BookState) value;
- (BookBuilder*) clearBookState;

- (BOOL) hasLastChapter;
- (Chapter*) lastChapter;
- (BookBuilder*) setLastChapter:(Chapter*) value;
- (BookBuilder*) setLastChapterBuilder:(ChapterBuilder*) builderForValue;
- (BookBuilder*) mergeLastChapter:(Chapter*) value;
- (BookBuilder*) clearLastChapter;
@end

#define BookNo_no @"no"
#define BookNo_name @"name"
@interface BookNo : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasName_:1;
  BOOL hasNo_:1;
  NSString* name;
  UInt32 no;
}
- (BOOL) hasNo;
- (BOOL) hasName;
@property (readonly) UInt32 no;
@property (readonly, strong) NSString* name;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BookNoBuilder*) builder;
+ (BookNoBuilder*) builder;
+ (BookNoBuilder*) builderWithPrototype:(BookNo*) prototype;
- (BookNoBuilder*) toBuilder;

+ (BookNo*) parseFromData:(NSData*) data;
+ (BookNo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookNo*) parseFromInputStream:(NSInputStream*) input;
+ (BookNo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookNo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BookNo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BookNoBuilder : PBGeneratedMessageBuilder {
@private
  BookNo* resultBookNo;
}

- (BookNo*) defaultInstance;

- (BookNoBuilder*) clear;
- (BookNoBuilder*) clone;

- (BookNo*) build;
- (BookNo*) buildPartial;

- (BookNoBuilder*) mergeFrom:(BookNo*) other;
- (BookNoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BookNoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNo;
- (UInt32) no;
- (BookNoBuilder*) setNo:(UInt32) value;
- (BookNoBuilder*) clearNo;

- (BOOL) hasName;
- (NSString*) name;
- (BookNoBuilder*) setName:(NSString*) value;
- (BookNoBuilder*) clearName;
@end

#define Source_id @"id"
#define Source_name @"name"
#define Source_url @"url"
#define Source_source_state @"sourceState"
#define Source_copyright_state @"copyrightState"
@interface Source : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasName_:1;
  BOOL hasUrl_:1;
  BOOL hasId_:1;
  BOOL hasSourceState_:1;
  BOOL hasCopyrightState_:1;
  NSString* name;
  NSString* url;
  UInt32 id;
  SourceState sourceState;
  CopyrightState copyrightState;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasUrl;
- (BOOL) hasSourceState;
- (BOOL) hasCopyrightState;
@property (readonly) UInt32 id;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* url;
@property (readonly) SourceState sourceState;
@property (readonly) CopyrightState copyrightState;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SourceBuilder*) builder;
+ (SourceBuilder*) builder;
+ (SourceBuilder*) builderWithPrototype:(Source*) prototype;
- (SourceBuilder*) toBuilder;

+ (Source*) parseFromData:(NSData*) data;
+ (Source*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Source*) parseFromInputStream:(NSInputStream*) input;
+ (Source*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Source*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Source*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SourceBuilder : PBGeneratedMessageBuilder {
@private
  Source* resultSource;
}

- (Source*) defaultInstance;

- (SourceBuilder*) clear;
- (SourceBuilder*) clone;

- (Source*) build;
- (Source*) buildPartial;

- (SourceBuilder*) mergeFrom:(Source*) other;
- (SourceBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SourceBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (UInt32) id;
- (SourceBuilder*) setId:(UInt32) value;
- (SourceBuilder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (SourceBuilder*) setName:(NSString*) value;
- (SourceBuilder*) clearName;

- (BOOL) hasUrl;
- (NSString*) url;
- (SourceBuilder*) setUrl:(NSString*) value;
- (SourceBuilder*) clearUrl;

- (BOOL) hasSourceState;
- (SourceState) sourceState;
- (SourceBuilder*) setSourceState:(SourceState) value;
- (SourceBuilder*) clearSourceState;

- (BOOL) hasCopyrightState;
- (CopyrightState) copyrightState;
- (SourceBuilder*) setCopyrightState:(CopyrightState) value;
- (SourceBuilder*) clearCopyrightState;
@end

#define Chapter_book @"book"
#define Chapter_book_no @"bookNo"
#define Chapter_chapter_no @"chapterNo"
#define Chapter_chapter_title @"chapterTitle"
#define Chapter_chapter_content @"chapterContent"
#define Chapter_source @"source"
#define Chapter_updated_at @"updatedAt"
@interface Chapter : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUpdatedAt_:1;
  BOOL hasChapterTitle_:1;
  BOOL hasChapterContent_:1;
  BOOL hasBook_:1;
  BOOL hasBookNo_:1;
  BOOL hasSource_:1;
  BOOL hasChapterNo_:1;
  UInt64 updatedAt;
  NSString* chapterTitle;
  NSString* chapterContent;
  Book* book;
  BookNo* bookNo;
  Source* source;
  UInt32 chapterNo;
}
- (BOOL) hasBook;
- (BOOL) hasBookNo;
- (BOOL) hasChapterNo;
- (BOOL) hasChapterTitle;
- (BOOL) hasChapterContent;
- (BOOL) hasSource;
- (BOOL) hasUpdatedAt;
@property (readonly, strong) Book* book;
@property (readonly, strong) BookNo* bookNo;
@property (readonly) UInt32 chapterNo;
@property (readonly, strong) NSString* chapterTitle;
@property (readonly, strong) NSString* chapterContent;
@property (readonly, strong) Source* source;
@property (readonly) UInt64 updatedAt;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChapterBuilder*) builder;
+ (ChapterBuilder*) builder;
+ (ChapterBuilder*) builderWithPrototype:(Chapter*) prototype;
- (ChapterBuilder*) toBuilder;

+ (Chapter*) parseFromData:(NSData*) data;
+ (Chapter*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Chapter*) parseFromInputStream:(NSInputStream*) input;
+ (Chapter*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Chapter*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Chapter*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChapterBuilder : PBGeneratedMessageBuilder {
@private
  Chapter* resultChapter;
}

- (Chapter*) defaultInstance;

- (ChapterBuilder*) clear;
- (ChapterBuilder*) clone;

- (Chapter*) build;
- (Chapter*) buildPartial;

- (ChapterBuilder*) mergeFrom:(Chapter*) other;
- (ChapterBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChapterBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBook;
- (Book*) book;
- (ChapterBuilder*) setBook:(Book*) value;
- (ChapterBuilder*) setBookBuilder:(BookBuilder*) builderForValue;
- (ChapterBuilder*) mergeBook:(Book*) value;
- (ChapterBuilder*) clearBook;

- (BOOL) hasBookNo;
- (BookNo*) bookNo;
- (ChapterBuilder*) setBookNo:(BookNo*) value;
- (ChapterBuilder*) setBookNoBuilder:(BookNoBuilder*) builderForValue;
- (ChapterBuilder*) mergeBookNo:(BookNo*) value;
- (ChapterBuilder*) clearBookNo;

- (BOOL) hasChapterNo;
- (UInt32) chapterNo;
- (ChapterBuilder*) setChapterNo:(UInt32) value;
- (ChapterBuilder*) clearChapterNo;

- (BOOL) hasChapterTitle;
- (NSString*) chapterTitle;
- (ChapterBuilder*) setChapterTitle:(NSString*) value;
- (ChapterBuilder*) clearChapterTitle;

- (BOOL) hasChapterContent;
- (NSString*) chapterContent;
- (ChapterBuilder*) setChapterContent:(NSString*) value;
- (ChapterBuilder*) clearChapterContent;

- (BOOL) hasSource;
- (Source*) source;
- (ChapterBuilder*) setSource:(Source*) value;
- (ChapterBuilder*) setSourceBuilder:(SourceBuilder*) builderForValue;
- (ChapterBuilder*) mergeSource:(Source*) value;
- (ChapterBuilder*) clearSource;

- (BOOL) hasUpdatedAt;
- (UInt64) updatedAt;
- (ChapterBuilder*) setUpdatedAt:(UInt64) value;
- (ChapterBuilder*) clearUpdatedAt;
@end

#define Device_device_type @"deviceType"
#define Device_os_type @"osType"
#define Device_os_version @"osVersion"
#define Device_vendor @"vendor"
#define Device_model @"model"
#define Device_udid @"udid"
#define Device_screen_size @"screenSize"
@interface Device : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOsVersion_:1;
  BOOL hasUdid_:1;
  BOOL hasScreenSize_:1;
  BOOL hasVendor_:1;
  BOOL hasModel_:1;
  BOOL hasDeviceType_:1;
  BOOL hasOsType_:1;
  NSString* osVersion;
  DeviceUdId* udid;
  DeviceSize* screenSize;
  NSData* vendor;
  NSData* model;
  DeviceDeviceType deviceType;
  DeviceOsType osType;
}
- (BOOL) hasDeviceType;
- (BOOL) hasOsType;
- (BOOL) hasOsVersion;
- (BOOL) hasVendor;
- (BOOL) hasModel;
- (BOOL) hasUdid;
- (BOOL) hasScreenSize;
@property (readonly) DeviceDeviceType deviceType;
@property (readonly) DeviceOsType osType;
@property (readonly, strong) NSString* osVersion;
@property (readonly, strong) NSData* vendor;
@property (readonly, strong) NSData* model;
@property (readonly, strong) DeviceUdId* udid;
@property (readonly, strong) DeviceSize* screenSize;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DeviceBuilder*) builder;
+ (DeviceBuilder*) builder;
+ (DeviceBuilder*) builderWithPrototype:(Device*) prototype;
- (DeviceBuilder*) toBuilder;

+ (Device*) parseFromData:(NSData*) data;
+ (Device*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Device*) parseFromInputStream:(NSInputStream*) input;
+ (Device*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Device*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Device*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define Size_width @"width"
#define Size_height @"height"
@interface DeviceSize : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasWidth_:1;
  BOOL hasHeight_:1;
  UInt32 width;
  UInt32 height;
}
- (BOOL) hasWidth;
- (BOOL) hasHeight;
@property (readonly) UInt32 width;
@property (readonly) UInt32 height;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DeviceSizeBuilder*) builder;
+ (DeviceSizeBuilder*) builder;
+ (DeviceSizeBuilder*) builderWithPrototype:(DeviceSize*) prototype;
- (DeviceSizeBuilder*) toBuilder;

+ (DeviceSize*) parseFromData:(NSData*) data;
+ (DeviceSize*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeviceSize*) parseFromInputStream:(NSInputStream*) input;
+ (DeviceSize*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeviceSize*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DeviceSize*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DeviceSizeBuilder : PBGeneratedMessageBuilder {
@private
  DeviceSize* resultSize;
}

- (DeviceSize*) defaultInstance;

- (DeviceSizeBuilder*) clear;
- (DeviceSizeBuilder*) clone;

- (DeviceSize*) build;
- (DeviceSize*) buildPartial;

- (DeviceSizeBuilder*) mergeFrom:(DeviceSize*) other;
- (DeviceSizeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DeviceSizeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasWidth;
- (UInt32) width;
- (DeviceSizeBuilder*) setWidth:(UInt32) value;
- (DeviceSizeBuilder*) clearWidth;

- (BOOL) hasHeight;
- (UInt32) height;
- (DeviceSizeBuilder*) setHeight:(UInt32) value;
- (DeviceSizeBuilder*) clearHeight;
@end

#define UdId_uuid @"uuid"
#define UdId_imei @"imei"
#define UdId_mac @"mac"
#define UdId_android_id @"androidId"
#define UdId_custom_id @"customId"
@interface DeviceUdId : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUuid_:1;
  BOOL hasImei_:1;
  BOOL hasMac_:1;
  BOOL hasAndroidId_:1;
  BOOL hasCustomId_:1;
  NSString* uuid;
  NSString* imei;
  NSString* mac;
  NSString* androidId;
  NSString* customId;
}
- (BOOL) hasUuid;
- (BOOL) hasImei;
- (BOOL) hasMac;
- (BOOL) hasAndroidId;
- (BOOL) hasCustomId;
@property (readonly, strong) NSString* uuid;
@property (readonly, strong) NSString* imei;
@property (readonly, strong) NSString* mac;
@property (readonly, strong) NSString* androidId;
@property (readonly, strong) NSString* customId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DeviceUdIdBuilder*) builder;
+ (DeviceUdIdBuilder*) builder;
+ (DeviceUdIdBuilder*) builderWithPrototype:(DeviceUdId*) prototype;
- (DeviceUdIdBuilder*) toBuilder;

+ (DeviceUdId*) parseFromData:(NSData*) data;
+ (DeviceUdId*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeviceUdId*) parseFromInputStream:(NSInputStream*) input;
+ (DeviceUdId*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeviceUdId*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DeviceUdId*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DeviceUdIdBuilder : PBGeneratedMessageBuilder {
@private
  DeviceUdId* resultUdId;
}

- (DeviceUdId*) defaultInstance;

- (DeviceUdIdBuilder*) clear;
- (DeviceUdIdBuilder*) clone;

- (DeviceUdId*) build;
- (DeviceUdId*) buildPartial;

- (DeviceUdIdBuilder*) mergeFrom:(DeviceUdId*) other;
- (DeviceUdIdBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DeviceUdIdBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUuid;
- (NSString*) uuid;
- (DeviceUdIdBuilder*) setUuid:(NSString*) value;
- (DeviceUdIdBuilder*) clearUuid;

- (BOOL) hasImei;
- (NSString*) imei;
- (DeviceUdIdBuilder*) setImei:(NSString*) value;
- (DeviceUdIdBuilder*) clearImei;

- (BOOL) hasMac;
- (NSString*) mac;
- (DeviceUdIdBuilder*) setMac:(NSString*) value;
- (DeviceUdIdBuilder*) clearMac;

- (BOOL) hasAndroidId;
- (NSString*) androidId;
- (DeviceUdIdBuilder*) setAndroidId:(NSString*) value;
- (DeviceUdIdBuilder*) clearAndroidId;

- (BOOL) hasCustomId;
- (NSString*) customId;
- (DeviceUdIdBuilder*) setCustomId:(NSString*) value;
- (DeviceUdIdBuilder*) clearCustomId;
@end

@interface DeviceBuilder : PBGeneratedMessageBuilder {
@private
  Device* resultDevice;
}

- (Device*) defaultInstance;

- (DeviceBuilder*) clear;
- (DeviceBuilder*) clone;

- (Device*) build;
- (Device*) buildPartial;

- (DeviceBuilder*) mergeFrom:(Device*) other;
- (DeviceBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DeviceBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDeviceType;
- (DeviceDeviceType) deviceType;
- (DeviceBuilder*) setDeviceType:(DeviceDeviceType) value;
- (DeviceBuilder*) clearDeviceType;

- (BOOL) hasOsType;
- (DeviceOsType) osType;
- (DeviceBuilder*) setOsType:(DeviceOsType) value;
- (DeviceBuilder*) clearOsType;

- (BOOL) hasOsVersion;
- (NSString*) osVersion;
- (DeviceBuilder*) setOsVersion:(NSString*) value;
- (DeviceBuilder*) clearOsVersion;

- (BOOL) hasVendor;
- (NSData*) vendor;
- (DeviceBuilder*) setVendor:(NSData*) value;
- (DeviceBuilder*) clearVendor;

- (BOOL) hasModel;
- (NSData*) model;
- (DeviceBuilder*) setModel:(NSData*) value;
- (DeviceBuilder*) clearModel;

- (BOOL) hasUdid;
- (DeviceUdId*) udid;
- (DeviceBuilder*) setUdid:(DeviceUdId*) value;
- (DeviceBuilder*) setUdidBuilder:(DeviceUdIdBuilder*) builderForValue;
- (DeviceBuilder*) mergeUdid:(DeviceUdId*) value;
- (DeviceBuilder*) clearUdid;

- (BOOL) hasScreenSize;
- (DeviceSize*) screenSize;
- (DeviceBuilder*) setScreenSize:(DeviceSize*) value;
- (DeviceBuilder*) setScreenSizeBuilder:(DeviceSizeBuilder*) builderForValue;
- (DeviceBuilder*) mergeScreenSize:(DeviceSize*) value;
- (DeviceBuilder*) clearScreenSize;
@end

#define FtBookApiReq_cmd @"cmd"
#define FtBookApiReq_device @"device"
#define FtBookApiReq_body @"body"
@interface FtBookApiReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasDevice_:1;
  BOOL hasBody_:1;
  BOOL hasCmd_:1;
  Device* device;
  NSData* body;
  UInt32 cmd;
}
- (BOOL) hasCmd;
- (BOOL) hasDevice;
- (BOOL) hasBody;
@property (readonly) UInt32 cmd;
@property (readonly, strong) Device* device;
@property (readonly, strong) NSData* body;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FtBookApiReqBuilder*) builder;
+ (FtBookApiReqBuilder*) builder;
+ (FtBookApiReqBuilder*) builderWithPrototype:(FtBookApiReq*) prototype;
- (FtBookApiReqBuilder*) toBuilder;

+ (FtBookApiReq*) parseFromData:(NSData*) data;
+ (FtBookApiReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FtBookApiReq*) parseFromInputStream:(NSInputStream*) input;
+ (FtBookApiReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FtBookApiReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FtBookApiReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FtBookApiReqBuilder : PBGeneratedMessageBuilder {
@private
  FtBookApiReq* resultFtBookApiReq;
}

- (FtBookApiReq*) defaultInstance;

- (FtBookApiReqBuilder*) clear;
- (FtBookApiReqBuilder*) clone;

- (FtBookApiReq*) build;
- (FtBookApiReq*) buildPartial;

- (FtBookApiReqBuilder*) mergeFrom:(FtBookApiReq*) other;
- (FtBookApiReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FtBookApiReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmd;
- (UInt32) cmd;
- (FtBookApiReqBuilder*) setCmd:(UInt32) value;
- (FtBookApiReqBuilder*) clearCmd;

- (BOOL) hasDevice;
- (Device*) device;
- (FtBookApiReqBuilder*) setDevice:(Device*) value;
- (FtBookApiReqBuilder*) setDeviceBuilder:(DeviceBuilder*) builderForValue;
- (FtBookApiReqBuilder*) mergeDevice:(Device*) value;
- (FtBookApiReqBuilder*) clearDevice;

- (BOOL) hasBody;
- (NSData*) body;
- (FtBookApiReqBuilder*) setBody:(NSData*) value;
- (FtBookApiReqBuilder*) clearBody;
@end

#define FtBookApiRes_cmd @"cmd"
#define FtBookApiRes_err @"err"
#define FtBookApiRes_body @"body"
@interface FtBookApiRes : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBody_:1;
  BOOL hasCmd_:1;
  BOOL hasErr_:1;
  NSData* body;
  UInt32 cmd;
  ErrCode err;
}
- (BOOL) hasCmd;
- (BOOL) hasErr;
- (BOOL) hasBody;
@property (readonly) UInt32 cmd;
@property (readonly) ErrCode err;
@property (readonly, strong) NSData* body;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FtBookApiResBuilder*) builder;
+ (FtBookApiResBuilder*) builder;
+ (FtBookApiResBuilder*) builderWithPrototype:(FtBookApiRes*) prototype;
- (FtBookApiResBuilder*) toBuilder;

+ (FtBookApiRes*) parseFromData:(NSData*) data;
+ (FtBookApiRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FtBookApiRes*) parseFromInputStream:(NSInputStream*) input;
+ (FtBookApiRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FtBookApiRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FtBookApiRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FtBookApiResBuilder : PBGeneratedMessageBuilder {
@private
  FtBookApiRes* resultFtBookApiRes;
}

- (FtBookApiRes*) defaultInstance;

- (FtBookApiResBuilder*) clear;
- (FtBookApiResBuilder*) clone;

- (FtBookApiRes*) build;
- (FtBookApiRes*) buildPartial;

- (FtBookApiResBuilder*) mergeFrom:(FtBookApiRes*) other;
- (FtBookApiResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FtBookApiResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmd;
- (UInt32) cmd;
- (FtBookApiResBuilder*) setCmd:(UInt32) value;
- (FtBookApiResBuilder*) clearCmd;

- (BOOL) hasErr;
- (ErrCode) err;
- (FtBookApiResBuilder*) setErr:(ErrCode) value;
- (FtBookApiResBuilder*) clearErr;

- (BOOL) hasBody;
- (NSData*) body;
- (FtBookApiResBuilder*) setBody:(NSData*) value;
- (FtBookApiResBuilder*) clearBody;
@end

#define FirstBookTypeReq_gender @"gender"
@interface FirstBookTypeReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGender_:1;
  GenderType gender;
}
- (BOOL) hasGender;
@property (readonly) GenderType gender;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FirstBookTypeReqBuilder*) builder;
+ (FirstBookTypeReqBuilder*) builder;
+ (FirstBookTypeReqBuilder*) builderWithPrototype:(FirstBookTypeReq*) prototype;
- (FirstBookTypeReqBuilder*) toBuilder;

+ (FirstBookTypeReq*) parseFromData:(NSData*) data;
+ (FirstBookTypeReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FirstBookTypeReq*) parseFromInputStream:(NSInputStream*) input;
+ (FirstBookTypeReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FirstBookTypeReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FirstBookTypeReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FirstBookTypeReqBuilder : PBGeneratedMessageBuilder {
@private
  FirstBookTypeReq* resultFirstBookTypeReq;
}

- (FirstBookTypeReq*) defaultInstance;

- (FirstBookTypeReqBuilder*) clear;
- (FirstBookTypeReqBuilder*) clone;

- (FirstBookTypeReq*) build;
- (FirstBookTypeReq*) buildPartial;

- (FirstBookTypeReqBuilder*) mergeFrom:(FirstBookTypeReq*) other;
- (FirstBookTypeReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FirstBookTypeReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGender;
- (GenderType) gender;
- (FirstBookTypeReqBuilder*) setGender:(GenderType) value;
- (FirstBookTypeReqBuilder*) clearGender;
@end

#define FirstBookTypeRes_book_type @"bookType"
@interface FirstBookTypeRes : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * bookTypeArray;
}
@property (readonly, strong) NSArray * bookType;
- (NSString*)bookTypeAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FirstBookTypeResBuilder*) builder;
+ (FirstBookTypeResBuilder*) builder;
+ (FirstBookTypeResBuilder*) builderWithPrototype:(FirstBookTypeRes*) prototype;
- (FirstBookTypeResBuilder*) toBuilder;

+ (FirstBookTypeRes*) parseFromData:(NSData*) data;
+ (FirstBookTypeRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FirstBookTypeRes*) parseFromInputStream:(NSInputStream*) input;
+ (FirstBookTypeRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FirstBookTypeRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FirstBookTypeRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FirstBookTypeResBuilder : PBGeneratedMessageBuilder {
@private
  FirstBookTypeRes* resultFirstBookTypeRes;
}

- (FirstBookTypeRes*) defaultInstance;

- (FirstBookTypeResBuilder*) clear;
- (FirstBookTypeResBuilder*) clone;

- (FirstBookTypeRes*) build;
- (FirstBookTypeRes*) buildPartial;

- (FirstBookTypeResBuilder*) mergeFrom:(FirstBookTypeRes*) other;
- (FirstBookTypeResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FirstBookTypeResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)bookType;
- (NSString*)bookTypeAtIndex:(NSUInteger)index;
- (FirstBookTypeResBuilder *)addBookType:(NSString*)value;
- (FirstBookTypeResBuilder *)setBookTypeArray:(NSArray *)array;
- (FirstBookTypeResBuilder *)clearBookType;
@end

#define FirstBookReq_gender @"gender"
#define FirstBookReq_book_type @"bookType"
@interface FirstBookReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGender_:1;
  GenderType gender;
  NSMutableArray * bookTypeArray;
}
- (BOOL) hasGender;
@property (readonly) GenderType gender;
@property (readonly, strong) NSArray * bookType;
- (NSString*)bookTypeAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FirstBookReqBuilder*) builder;
+ (FirstBookReqBuilder*) builder;
+ (FirstBookReqBuilder*) builderWithPrototype:(FirstBookReq*) prototype;
- (FirstBookReqBuilder*) toBuilder;

+ (FirstBookReq*) parseFromData:(NSData*) data;
+ (FirstBookReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FirstBookReq*) parseFromInputStream:(NSInputStream*) input;
+ (FirstBookReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FirstBookReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FirstBookReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FirstBookReqBuilder : PBGeneratedMessageBuilder {
@private
  FirstBookReq* resultFirstBookReq;
}

- (FirstBookReq*) defaultInstance;

- (FirstBookReqBuilder*) clear;
- (FirstBookReqBuilder*) clone;

- (FirstBookReq*) build;
- (FirstBookReq*) buildPartial;

- (FirstBookReqBuilder*) mergeFrom:(FirstBookReq*) other;
- (FirstBookReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FirstBookReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGender;
- (GenderType) gender;
- (FirstBookReqBuilder*) setGender:(GenderType) value;
- (FirstBookReqBuilder*) clearGender;

- (NSMutableArray *)bookType;
- (NSString*)bookTypeAtIndex:(NSUInteger)index;
- (FirstBookReqBuilder *)addBookType:(NSString*)value;
- (FirstBookReqBuilder *)setBookTypeArray:(NSArray *)array;
- (FirstBookReqBuilder *)clearBookType;
@end

#define FirstBookRes_books @"books"
@interface FirstBookRes : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * booksArray;
}
@property (readonly, strong) NSArray<Book*> * books;
- (Book*)booksAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FirstBookResBuilder*) builder;
+ (FirstBookResBuilder*) builder;
+ (FirstBookResBuilder*) builderWithPrototype:(FirstBookRes*) prototype;
- (FirstBookResBuilder*) toBuilder;

+ (FirstBookRes*) parseFromData:(NSData*) data;
+ (FirstBookRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FirstBookRes*) parseFromInputStream:(NSInputStream*) input;
+ (FirstBookRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FirstBookRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FirstBookRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FirstBookResBuilder : PBGeneratedMessageBuilder {
@private
  FirstBookRes* resultFirstBookRes;
}

- (FirstBookRes*) defaultInstance;

- (FirstBookResBuilder*) clear;
- (FirstBookResBuilder*) clone;

- (FirstBookRes*) build;
- (FirstBookRes*) buildPartial;

- (FirstBookResBuilder*) mergeFrom:(FirstBookRes*) other;
- (FirstBookResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FirstBookResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray<Book*> *)books;
- (Book*)booksAtIndex:(NSUInteger)index;
- (FirstBookResBuilder *)addBooks:(Book*)value;
- (FirstBookResBuilder *)setBooksArray:(NSArray<Book*> *)array;
- (FirstBookResBuilder *)clearBooks;
@end

#define UserBookStoreReq_page @"page"
@interface UserBookStoreReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPage_:1;
  UInt32 page;
}
- (BOOL) hasPage;
@property (readonly) UInt32 page;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserBookStoreReqBuilder*) builder;
+ (UserBookStoreReqBuilder*) builder;
+ (UserBookStoreReqBuilder*) builderWithPrototype:(UserBookStoreReq*) prototype;
- (UserBookStoreReqBuilder*) toBuilder;

+ (UserBookStoreReq*) parseFromData:(NSData*) data;
+ (UserBookStoreReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserBookStoreReq*) parseFromInputStream:(NSInputStream*) input;
+ (UserBookStoreReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserBookStoreReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserBookStoreReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserBookStoreReqBuilder : PBGeneratedMessageBuilder {
@private
  UserBookStoreReq* resultUserBookStoreReq;
}

- (UserBookStoreReq*) defaultInstance;

- (UserBookStoreReqBuilder*) clear;
- (UserBookStoreReqBuilder*) clone;

- (UserBookStoreReq*) build;
- (UserBookStoreReq*) buildPartial;

- (UserBookStoreReqBuilder*) mergeFrom:(UserBookStoreReq*) other;
- (UserBookStoreReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserBookStoreReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPage;
- (UInt32) page;
- (UserBookStoreReqBuilder*) setPage:(UInt32) value;
- (UserBookStoreReqBuilder*) clearPage;
@end

#define UserBook_book @"book"
#define UserBook_is_top @"isTop"
@interface UserBook : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBook_:1;
  BOOL hasIsTop_:1;
  Book* book;
  UInt32 isTop;
}
- (BOOL) hasBook;
- (BOOL) hasIsTop;
@property (readonly, strong) Book* book;
@property (readonly) UInt32 isTop;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserBookBuilder*) builder;
+ (UserBookBuilder*) builder;
+ (UserBookBuilder*) builderWithPrototype:(UserBook*) prototype;
- (UserBookBuilder*) toBuilder;

+ (UserBook*) parseFromData:(NSData*) data;
+ (UserBook*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserBook*) parseFromInputStream:(NSInputStream*) input;
+ (UserBook*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserBook*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserBook*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserBookBuilder : PBGeneratedMessageBuilder {
@private
  UserBook* resultUserBook;
}

- (UserBook*) defaultInstance;

- (UserBookBuilder*) clear;
- (UserBookBuilder*) clone;

- (UserBook*) build;
- (UserBook*) buildPartial;

- (UserBookBuilder*) mergeFrom:(UserBook*) other;
- (UserBookBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserBookBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBook;
- (Book*) book;
- (UserBookBuilder*) setBook:(Book*) value;
- (UserBookBuilder*) setBookBuilder:(BookBuilder*) builderForValue;
- (UserBookBuilder*) mergeBook:(Book*) value;
- (UserBookBuilder*) clearBook;

- (BOOL) hasIsTop;
- (UInt32) isTop;
- (UserBookBuilder*) setIsTop:(UInt32) value;
- (UserBookBuilder*) clearIsTop;
@end

#define UserBookStoreRes_psize @"psize"
#define UserBookStoreRes_page @"page"
#define UserBookStoreRes_user_books @"userBooks"
@interface UserBookStoreRes : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPsize_:1;
  BOOL hasPage_:1;
  UInt32 psize;
  UInt32 page;
  NSMutableArray * userBooksArray;
}
- (BOOL) hasPsize;
- (BOOL) hasPage;
@property (readonly) UInt32 psize;
@property (readonly) UInt32 page;
@property (readonly, strong) NSArray<UserBook*> * userBooks;
- (UserBook*)userBooksAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserBookStoreResBuilder*) builder;
+ (UserBookStoreResBuilder*) builder;
+ (UserBookStoreResBuilder*) builderWithPrototype:(UserBookStoreRes*) prototype;
- (UserBookStoreResBuilder*) toBuilder;

+ (UserBookStoreRes*) parseFromData:(NSData*) data;
+ (UserBookStoreRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserBookStoreRes*) parseFromInputStream:(NSInputStream*) input;
+ (UserBookStoreRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserBookStoreRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserBookStoreRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserBookStoreResBuilder : PBGeneratedMessageBuilder {
@private
  UserBookStoreRes* resultUserBookStoreRes;
}

- (UserBookStoreRes*) defaultInstance;

- (UserBookStoreResBuilder*) clear;
- (UserBookStoreResBuilder*) clone;

- (UserBookStoreRes*) build;
- (UserBookStoreRes*) buildPartial;

- (UserBookStoreResBuilder*) mergeFrom:(UserBookStoreRes*) other;
- (UserBookStoreResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserBookStoreResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPsize;
- (UInt32) psize;
- (UserBookStoreResBuilder*) setPsize:(UInt32) value;
- (UserBookStoreResBuilder*) clearPsize;

- (BOOL) hasPage;
- (UInt32) page;
- (UserBookStoreResBuilder*) setPage:(UInt32) value;
- (UserBookStoreResBuilder*) clearPage;

- (NSMutableArray<UserBook*> *)userBooks;
- (UserBook*)userBooksAtIndex:(NSUInteger)index;
- (UserBookStoreResBuilder *)addUserBooks:(UserBook*)value;
- (UserBookStoreResBuilder *)setUserBooksArray:(NSArray<UserBook*> *)array;
- (UserBookStoreResBuilder *)clearUserBooks;
@end

#define UserBookStoreOperateReq_type @"type"
#define UserBookStoreOperateReq_book_id @"bookId"
@interface UserBookStoreOperateReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBookId_:1;
  BOOL hasType_:1;
  UInt32 bookId;
  UserBookStoreOperateType type;
}
- (BOOL) hasType;
- (BOOL) hasBookId;
@property (readonly) UserBookStoreOperateType type;
@property (readonly) UInt32 bookId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserBookStoreOperateReqBuilder*) builder;
+ (UserBookStoreOperateReqBuilder*) builder;
+ (UserBookStoreOperateReqBuilder*) builderWithPrototype:(UserBookStoreOperateReq*) prototype;
- (UserBookStoreOperateReqBuilder*) toBuilder;

+ (UserBookStoreOperateReq*) parseFromData:(NSData*) data;
+ (UserBookStoreOperateReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserBookStoreOperateReq*) parseFromInputStream:(NSInputStream*) input;
+ (UserBookStoreOperateReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserBookStoreOperateReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserBookStoreOperateReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserBookStoreOperateReqBuilder : PBGeneratedMessageBuilder {
@private
  UserBookStoreOperateReq* resultUserBookStoreOperateReq;
}

- (UserBookStoreOperateReq*) defaultInstance;

- (UserBookStoreOperateReqBuilder*) clear;
- (UserBookStoreOperateReqBuilder*) clone;

- (UserBookStoreOperateReq*) build;
- (UserBookStoreOperateReq*) buildPartial;

- (UserBookStoreOperateReqBuilder*) mergeFrom:(UserBookStoreOperateReq*) other;
- (UserBookStoreOperateReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserBookStoreOperateReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (UserBookStoreOperateType) type;
- (UserBookStoreOperateReqBuilder*) setType:(UserBookStoreOperateType) value;
- (UserBookStoreOperateReqBuilder*) clearType;

- (BOOL) hasBookId;
- (UInt32) bookId;
- (UserBookStoreOperateReqBuilder*) setBookId:(UInt32) value;
- (UserBookStoreOperateReqBuilder*) clearBookId;
@end

#define BookStoreReq_book_type @"bookType"
#define BookStoreReq_page @"page"
#define BookStoreReq_is_finished @"isFinished"
#define BookStoreReq_is_new @"isNew"
@interface BookStoreReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPage_:1;
  BOOL hasIsFinished_:1;
  BOOL hasIsNew_:1;
  UInt32 page;
  UInt32 isFinished;
  UInt32 isNew;
  NSMutableArray * bookTypeArray;
}
- (BOOL) hasPage;
- (BOOL) hasIsFinished;
- (BOOL) hasIsNew;
@property (readonly, strong) NSArray * bookType;
@property (readonly) UInt32 page;
@property (readonly) UInt32 isFinished;
@property (readonly) UInt32 isNew;
- (NSString*)bookTypeAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BookStoreReqBuilder*) builder;
+ (BookStoreReqBuilder*) builder;
+ (BookStoreReqBuilder*) builderWithPrototype:(BookStoreReq*) prototype;
- (BookStoreReqBuilder*) toBuilder;

+ (BookStoreReq*) parseFromData:(NSData*) data;
+ (BookStoreReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookStoreReq*) parseFromInputStream:(NSInputStream*) input;
+ (BookStoreReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookStoreReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BookStoreReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BookStoreReqBuilder : PBGeneratedMessageBuilder {
@private
  BookStoreReq* resultBookStoreReq;
}

- (BookStoreReq*) defaultInstance;

- (BookStoreReqBuilder*) clear;
- (BookStoreReqBuilder*) clone;

- (BookStoreReq*) build;
- (BookStoreReq*) buildPartial;

- (BookStoreReqBuilder*) mergeFrom:(BookStoreReq*) other;
- (BookStoreReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BookStoreReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)bookType;
- (NSString*)bookTypeAtIndex:(NSUInteger)index;
- (BookStoreReqBuilder *)addBookType:(NSString*)value;
- (BookStoreReqBuilder *)setBookTypeArray:(NSArray *)array;
- (BookStoreReqBuilder *)clearBookType;

- (BOOL) hasPage;
- (UInt32) page;
- (BookStoreReqBuilder*) setPage:(UInt32) value;
- (BookStoreReqBuilder*) clearPage;

- (BOOL) hasIsFinished;
- (UInt32) isFinished;
- (BookStoreReqBuilder*) setIsFinished:(UInt32) value;
- (BookStoreReqBuilder*) clearIsFinished;

- (BOOL) hasIsNew;
- (UInt32) isNew;
- (BookStoreReqBuilder*) setIsNew:(UInt32) value;
- (BookStoreReqBuilder*) clearIsNew;
@end

#define BookStoreRes_psize @"psize"
#define BookStoreRes_page @"page"
#define BookStoreRes_books @"books"
@interface BookStoreRes : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPsize_:1;
  BOOL hasPage_:1;
  UInt32 psize;
  UInt32 page;
  NSMutableArray * booksArray;
}
- (BOOL) hasPsize;
- (BOOL) hasPage;
@property (readonly) UInt32 psize;
@property (readonly) UInt32 page;
@property (readonly, strong) NSArray<Book*> * books;
- (Book*)booksAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BookStoreResBuilder*) builder;
+ (BookStoreResBuilder*) builder;
+ (BookStoreResBuilder*) builderWithPrototype:(BookStoreRes*) prototype;
- (BookStoreResBuilder*) toBuilder;

+ (BookStoreRes*) parseFromData:(NSData*) data;
+ (BookStoreRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookStoreRes*) parseFromInputStream:(NSInputStream*) input;
+ (BookStoreRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookStoreRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BookStoreRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BookStoreResBuilder : PBGeneratedMessageBuilder {
@private
  BookStoreRes* resultBookStoreRes;
}

- (BookStoreRes*) defaultInstance;

- (BookStoreResBuilder*) clear;
- (BookStoreResBuilder*) clone;

- (BookStoreRes*) build;
- (BookStoreRes*) buildPartial;

- (BookStoreResBuilder*) mergeFrom:(BookStoreRes*) other;
- (BookStoreResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BookStoreResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPsize;
- (UInt32) psize;
- (BookStoreResBuilder*) setPsize:(UInt32) value;
- (BookStoreResBuilder*) clearPsize;

- (BOOL) hasPage;
- (UInt32) page;
- (BookStoreResBuilder*) setPage:(UInt32) value;
- (BookStoreResBuilder*) clearPage;

- (NSMutableArray<Book*> *)books;
- (Book*)booksAtIndex:(NSUInteger)index;
- (BookStoreResBuilder *)addBooks:(Book*)value;
- (BookStoreResBuilder *)setBooksArray:(NSArray<Book*> *)array;
- (BookStoreResBuilder *)clearBooks;
@end

#define BookSearchReq_kw @"kw"
#define BookSearchReq_page @"page"
@interface BookSearchReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasKw_:1;
  BOOL hasPage_:1;
  NSString* kw;
  UInt32 page;
}
- (BOOL) hasKw;
- (BOOL) hasPage;
@property (readonly, strong) NSString* kw;
@property (readonly) UInt32 page;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BookSearchReqBuilder*) builder;
+ (BookSearchReqBuilder*) builder;
+ (BookSearchReqBuilder*) builderWithPrototype:(BookSearchReq*) prototype;
- (BookSearchReqBuilder*) toBuilder;

+ (BookSearchReq*) parseFromData:(NSData*) data;
+ (BookSearchReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookSearchReq*) parseFromInputStream:(NSInputStream*) input;
+ (BookSearchReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookSearchReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BookSearchReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BookSearchReqBuilder : PBGeneratedMessageBuilder {
@private
  BookSearchReq* resultBookSearchReq;
}

- (BookSearchReq*) defaultInstance;

- (BookSearchReqBuilder*) clear;
- (BookSearchReqBuilder*) clone;

- (BookSearchReq*) build;
- (BookSearchReq*) buildPartial;

- (BookSearchReqBuilder*) mergeFrom:(BookSearchReq*) other;
- (BookSearchReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BookSearchReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasKw;
- (NSString*) kw;
- (BookSearchReqBuilder*) setKw:(NSString*) value;
- (BookSearchReqBuilder*) clearKw;

- (BOOL) hasPage;
- (UInt32) page;
- (BookSearchReqBuilder*) setPage:(UInt32) value;
- (BookSearchReqBuilder*) clearPage;
@end

#define BookSearchRes_psize @"psize"
#define BookSearchRes_page @"page"
#define BookSearchRes_books @"books"
#define BookSearchRes_relate_books @"relateBooks"
@interface BookSearchRes : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPsize_:1;
  BOOL hasPage_:1;
  UInt32 psize;
  UInt32 page;
  NSMutableArray * booksArray;
  NSMutableArray * relateBooksArray;
}
- (BOOL) hasPsize;
- (BOOL) hasPage;
@property (readonly) UInt32 psize;
@property (readonly) UInt32 page;
@property (readonly, strong) NSArray<Book*> * books;
@property (readonly, strong) NSArray<Book*> * relateBooks;
- (Book*)booksAtIndex:(NSUInteger)index;
- (Book*)relateBooksAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BookSearchResBuilder*) builder;
+ (BookSearchResBuilder*) builder;
+ (BookSearchResBuilder*) builderWithPrototype:(BookSearchRes*) prototype;
- (BookSearchResBuilder*) toBuilder;

+ (BookSearchRes*) parseFromData:(NSData*) data;
+ (BookSearchRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookSearchRes*) parseFromInputStream:(NSInputStream*) input;
+ (BookSearchRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookSearchRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BookSearchRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BookSearchResBuilder : PBGeneratedMessageBuilder {
@private
  BookSearchRes* resultBookSearchRes;
}

- (BookSearchRes*) defaultInstance;

- (BookSearchResBuilder*) clear;
- (BookSearchResBuilder*) clone;

- (BookSearchRes*) build;
- (BookSearchRes*) buildPartial;

- (BookSearchResBuilder*) mergeFrom:(BookSearchRes*) other;
- (BookSearchResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BookSearchResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPsize;
- (UInt32) psize;
- (BookSearchResBuilder*) setPsize:(UInt32) value;
- (BookSearchResBuilder*) clearPsize;

- (BOOL) hasPage;
- (UInt32) page;
- (BookSearchResBuilder*) setPage:(UInt32) value;
- (BookSearchResBuilder*) clearPage;

- (NSMutableArray<Book*> *)books;
- (Book*)booksAtIndex:(NSUInteger)index;
- (BookSearchResBuilder *)addBooks:(Book*)value;
- (BookSearchResBuilder *)setBooksArray:(NSArray<Book*> *)array;
- (BookSearchResBuilder *)clearBooks;

- (NSMutableArray<Book*> *)relateBooks;
- (Book*)relateBooksAtIndex:(NSUInteger)index;
- (BookSearchResBuilder *)addRelateBooks:(Book*)value;
- (BookSearchResBuilder *)setRelateBooksArray:(NSArray<Book*> *)array;
- (BookSearchResBuilder *)clearRelateBooks;
@end

#define BookChapterReq_book_id @"bookId"
@interface BookChapterReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBookId_:1;
  UInt32 bookId;
}
- (BOOL) hasBookId;
@property (readonly) UInt32 bookId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BookChapterReqBuilder*) builder;
+ (BookChapterReqBuilder*) builder;
+ (BookChapterReqBuilder*) builderWithPrototype:(BookChapterReq*) prototype;
- (BookChapterReqBuilder*) toBuilder;

+ (BookChapterReq*) parseFromData:(NSData*) data;
+ (BookChapterReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookChapterReq*) parseFromInputStream:(NSInputStream*) input;
+ (BookChapterReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookChapterReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BookChapterReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BookChapterReqBuilder : PBGeneratedMessageBuilder {
@private
  BookChapterReq* resultBookChapterReq;
}

- (BookChapterReq*) defaultInstance;

- (BookChapterReqBuilder*) clear;
- (BookChapterReqBuilder*) clone;

- (BookChapterReq*) build;
- (BookChapterReq*) buildPartial;

- (BookChapterReqBuilder*) mergeFrom:(BookChapterReq*) other;
- (BookChapterReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BookChapterReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBookId;
- (UInt32) bookId;
- (BookChapterReqBuilder*) setBookId:(UInt32) value;
- (BookChapterReqBuilder*) clearBookId;
@end

#define BookChapterRes_chapters @"chapters"
@interface BookChapterRes : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * chaptersArray;
}
@property (readonly, strong) NSArray<Chapter*> * chapters;
- (Chapter*)chaptersAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BookChapterResBuilder*) builder;
+ (BookChapterResBuilder*) builder;
+ (BookChapterResBuilder*) builderWithPrototype:(BookChapterRes*) prototype;
- (BookChapterResBuilder*) toBuilder;

+ (BookChapterRes*) parseFromData:(NSData*) data;
+ (BookChapterRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookChapterRes*) parseFromInputStream:(NSInputStream*) input;
+ (BookChapterRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookChapterRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BookChapterRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BookChapterResBuilder : PBGeneratedMessageBuilder {
@private
  BookChapterRes* resultBookChapterRes;
}

- (BookChapterRes*) defaultInstance;

- (BookChapterResBuilder*) clear;
- (BookChapterResBuilder*) clone;

- (BookChapterRes*) build;
- (BookChapterRes*) buildPartial;

- (BookChapterResBuilder*) mergeFrom:(BookChapterRes*) other;
- (BookChapterResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BookChapterResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray<Chapter*> *)chapters;
- (Chapter*)chaptersAtIndex:(NSUInteger)index;
- (BookChapterResBuilder *)addChapters:(Chapter*)value;
- (BookChapterResBuilder *)setChaptersArray:(NSArray<Chapter*> *)array;
- (BookChapterResBuilder *)clearChapters;
@end

#define BookChapterSourceReq_book_id @"bookId"
#define BookChapterSourceReq_chapter_no @"chapterNo"
#define BookChapterSourceReq_chapter_title @"chapterTitle"
#define BookChapterSourceReq_source_id @"sourceId"
@interface BookChapterSourceReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChapterTitle_:1;
  BOOL hasBookId_:1;
  BOOL hasChapterNo_:1;
  BOOL hasSourceId_:1;
  NSString* chapterTitle;
  UInt32 bookId;
  UInt32 chapterNo;
  UInt32 sourceId;
}
- (BOOL) hasBookId;
- (BOOL) hasChapterNo;
- (BOOL) hasChapterTitle;
- (BOOL) hasSourceId;
@property (readonly) UInt32 bookId;
@property (readonly) UInt32 chapterNo;
@property (readonly, strong) NSString* chapterTitle;
@property (readonly) UInt32 sourceId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BookChapterSourceReqBuilder*) builder;
+ (BookChapterSourceReqBuilder*) builder;
+ (BookChapterSourceReqBuilder*) builderWithPrototype:(BookChapterSourceReq*) prototype;
- (BookChapterSourceReqBuilder*) toBuilder;

+ (BookChapterSourceReq*) parseFromData:(NSData*) data;
+ (BookChapterSourceReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookChapterSourceReq*) parseFromInputStream:(NSInputStream*) input;
+ (BookChapterSourceReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookChapterSourceReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BookChapterSourceReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BookChapterSourceReqBuilder : PBGeneratedMessageBuilder {
@private
  BookChapterSourceReq* resultBookChapterSourceReq;
}

- (BookChapterSourceReq*) defaultInstance;

- (BookChapterSourceReqBuilder*) clear;
- (BookChapterSourceReqBuilder*) clone;

- (BookChapterSourceReq*) build;
- (BookChapterSourceReq*) buildPartial;

- (BookChapterSourceReqBuilder*) mergeFrom:(BookChapterSourceReq*) other;
- (BookChapterSourceReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BookChapterSourceReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBookId;
- (UInt32) bookId;
- (BookChapterSourceReqBuilder*) setBookId:(UInt32) value;
- (BookChapterSourceReqBuilder*) clearBookId;

- (BOOL) hasChapterNo;
- (UInt32) chapterNo;
- (BookChapterSourceReqBuilder*) setChapterNo:(UInt32) value;
- (BookChapterSourceReqBuilder*) clearChapterNo;

- (BOOL) hasChapterTitle;
- (NSString*) chapterTitle;
- (BookChapterSourceReqBuilder*) setChapterTitle:(NSString*) value;
- (BookChapterSourceReqBuilder*) clearChapterTitle;

- (BOOL) hasSourceId;
- (UInt32) sourceId;
- (BookChapterSourceReqBuilder*) setSourceId:(UInt32) value;
- (BookChapterSourceReqBuilder*) clearSourceId;
@end

#define SourceLastChapter_source @"source"
#define SourceLastChapter_last_chapter @"lastChapter"
@interface SourceLastChapter : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSource_:1;
  BOOL hasLastChapter_:1;
  Source* source;
  Chapter* lastChapter;
}
- (BOOL) hasSource;
- (BOOL) hasLastChapter;
@property (readonly, strong) Source* source;
@property (readonly, strong) Chapter* lastChapter;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SourceLastChapterBuilder*) builder;
+ (SourceLastChapterBuilder*) builder;
+ (SourceLastChapterBuilder*) builderWithPrototype:(SourceLastChapter*) prototype;
- (SourceLastChapterBuilder*) toBuilder;

+ (SourceLastChapter*) parseFromData:(NSData*) data;
+ (SourceLastChapter*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SourceLastChapter*) parseFromInputStream:(NSInputStream*) input;
+ (SourceLastChapter*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SourceLastChapter*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SourceLastChapter*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SourceLastChapterBuilder : PBGeneratedMessageBuilder {
@private
  SourceLastChapter* resultSourceLastChapter;
}

- (SourceLastChapter*) defaultInstance;

- (SourceLastChapterBuilder*) clear;
- (SourceLastChapterBuilder*) clone;

- (SourceLastChapter*) build;
- (SourceLastChapter*) buildPartial;

- (SourceLastChapterBuilder*) mergeFrom:(SourceLastChapter*) other;
- (SourceLastChapterBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SourceLastChapterBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSource;
- (Source*) source;
- (SourceLastChapterBuilder*) setSource:(Source*) value;
- (SourceLastChapterBuilder*) setSourceBuilder:(SourceBuilder*) builderForValue;
- (SourceLastChapterBuilder*) mergeSource:(Source*) value;
- (SourceLastChapterBuilder*) clearSource;

- (BOOL) hasLastChapter;
- (Chapter*) lastChapter;
- (SourceLastChapterBuilder*) setLastChapter:(Chapter*) value;
- (SourceLastChapterBuilder*) setLastChapterBuilder:(ChapterBuilder*) builderForValue;
- (SourceLastChapterBuilder*) mergeLastChapter:(Chapter*) value;
- (SourceLastChapterBuilder*) clearLastChapter;
@end

#define BookChapterSourceRes_chapter @"chapter"
#define BookChapterSourceRes_sources @"sources"
@interface BookChapterSourceRes : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChapter_:1;
  Chapter* chapter;
  NSMutableArray * sourcesArray;
}
- (BOOL) hasChapter;
@property (readonly, strong) Chapter* chapter;
@property (readonly, strong) NSArray<SourceLastChapter*> * sources;
- (SourceLastChapter*)sourcesAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BookChapterSourceResBuilder*) builder;
+ (BookChapterSourceResBuilder*) builder;
+ (BookChapterSourceResBuilder*) builderWithPrototype:(BookChapterSourceRes*) prototype;
- (BookChapterSourceResBuilder*) toBuilder;

+ (BookChapterSourceRes*) parseFromData:(NSData*) data;
+ (BookChapterSourceRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookChapterSourceRes*) parseFromInputStream:(NSInputStream*) input;
+ (BookChapterSourceRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookChapterSourceRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BookChapterSourceRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BookChapterSourceResBuilder : PBGeneratedMessageBuilder {
@private
  BookChapterSourceRes* resultBookChapterSourceRes;
}

- (BookChapterSourceRes*) defaultInstance;

- (BookChapterSourceResBuilder*) clear;
- (BookChapterSourceResBuilder*) clone;

- (BookChapterSourceRes*) build;
- (BookChapterSourceRes*) buildPartial;

- (BookChapterSourceResBuilder*) mergeFrom:(BookChapterSourceRes*) other;
- (BookChapterSourceResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BookChapterSourceResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChapter;
- (Chapter*) chapter;
- (BookChapterSourceResBuilder*) setChapter:(Chapter*) value;
- (BookChapterSourceResBuilder*) setChapterBuilder:(ChapterBuilder*) builderForValue;
- (BookChapterSourceResBuilder*) mergeChapter:(Chapter*) value;
- (BookChapterSourceResBuilder*) clearChapter;

- (NSMutableArray<SourceLastChapter*> *)sources;
- (SourceLastChapter*)sourcesAtIndex:(NSUInteger)index;
- (BookChapterSourceResBuilder *)addSources:(SourceLastChapter*)value;
- (BookChapterSourceResBuilder *)setSourcesArray:(NSArray<SourceLastChapter*> *)array;
- (BookChapterSourceResBuilder *)clearSources;
@end

#define BookRelateReq_book_id @"bookId"
@interface BookRelateReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBookId_:1;
  UInt32 bookId;
}
- (BOOL) hasBookId;
@property (readonly) UInt32 bookId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BookRelateReqBuilder*) builder;
+ (BookRelateReqBuilder*) builder;
+ (BookRelateReqBuilder*) builderWithPrototype:(BookRelateReq*) prototype;
- (BookRelateReqBuilder*) toBuilder;

+ (BookRelateReq*) parseFromData:(NSData*) data;
+ (BookRelateReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookRelateReq*) parseFromInputStream:(NSInputStream*) input;
+ (BookRelateReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookRelateReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BookRelateReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BookRelateReqBuilder : PBGeneratedMessageBuilder {
@private
  BookRelateReq* resultBookRelateReq;
}

- (BookRelateReq*) defaultInstance;

- (BookRelateReqBuilder*) clear;
- (BookRelateReqBuilder*) clone;

- (BookRelateReq*) build;
- (BookRelateReq*) buildPartial;

- (BookRelateReqBuilder*) mergeFrom:(BookRelateReq*) other;
- (BookRelateReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BookRelateReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBookId;
- (UInt32) bookId;
- (BookRelateReqBuilder*) setBookId:(UInt32) value;
- (BookRelateReqBuilder*) clearBookId;
@end

#define BookRelateRes_have_add @"haveAdd"
#define BookRelateRes_relate_books @"relateBooks"
@interface BookRelateRes : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasHaveAdd_:1;
  UInt32 haveAdd;
  NSMutableArray * relateBooksArray;
}
- (BOOL) hasHaveAdd;
@property (readonly) UInt32 haveAdd;
@property (readonly, strong) NSArray<Book*> * relateBooks;
- (Book*)relateBooksAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BookRelateResBuilder*) builder;
+ (BookRelateResBuilder*) builder;
+ (BookRelateResBuilder*) builderWithPrototype:(BookRelateRes*) prototype;
- (BookRelateResBuilder*) toBuilder;

+ (BookRelateRes*) parseFromData:(NSData*) data;
+ (BookRelateRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookRelateRes*) parseFromInputStream:(NSInputStream*) input;
+ (BookRelateRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookRelateRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BookRelateRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BookRelateResBuilder : PBGeneratedMessageBuilder {
@private
  BookRelateRes* resultBookRelateRes;
}

- (BookRelateRes*) defaultInstance;

- (BookRelateResBuilder*) clear;
- (BookRelateResBuilder*) clone;

- (BookRelateRes*) build;
- (BookRelateRes*) buildPartial;

- (BookRelateResBuilder*) mergeFrom:(BookRelateRes*) other;
- (BookRelateResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BookRelateResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasHaveAdd;
- (UInt32) haveAdd;
- (BookRelateResBuilder*) setHaveAdd:(UInt32) value;
- (BookRelateResBuilder*) clearHaveAdd;

- (NSMutableArray<Book*> *)relateBooks;
- (Book*)relateBooksAtIndex:(NSUInteger)index;
- (BookRelateResBuilder *)addRelateBooks:(Book*)value;
- (BookRelateResBuilder *)setRelateBooksArray:(NSArray<Book*> *)array;
- (BookRelateResBuilder *)clearRelateBooks;
@end

#define TopicHomeReq_type @"type"
#define TopicHomeReq_page @"page"
@interface TopicHomeReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasType_:1;
  BOOL hasPage_:1;
  UInt32 type;
  UInt32 page;
}
- (BOOL) hasType;
- (BOOL) hasPage;
@property (readonly) UInt32 type;
@property (readonly) UInt32 page;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TopicHomeReqBuilder*) builder;
+ (TopicHomeReqBuilder*) builder;
+ (TopicHomeReqBuilder*) builderWithPrototype:(TopicHomeReq*) prototype;
- (TopicHomeReqBuilder*) toBuilder;

+ (TopicHomeReq*) parseFromData:(NSData*) data;
+ (TopicHomeReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TopicHomeReq*) parseFromInputStream:(NSInputStream*) input;
+ (TopicHomeReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TopicHomeReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TopicHomeReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TopicHomeReqBuilder : PBGeneratedMessageBuilder {
@private
  TopicHomeReq* resultTopicHomeReq;
}

- (TopicHomeReq*) defaultInstance;

- (TopicHomeReqBuilder*) clear;
- (TopicHomeReqBuilder*) clone;

- (TopicHomeReq*) build;
- (TopicHomeReq*) buildPartial;

- (TopicHomeReqBuilder*) mergeFrom:(TopicHomeReq*) other;
- (TopicHomeReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TopicHomeReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (UInt32) type;
- (TopicHomeReqBuilder*) setType:(UInt32) value;
- (TopicHomeReqBuilder*) clearType;

- (BOOL) hasPage;
- (UInt32) page;
- (TopicHomeReqBuilder*) setPage:(UInt32) value;
- (TopicHomeReqBuilder*) clearPage;
@end

#define TopicHomeRes_interest_books @"interestBooks"
#define TopicHomeRes_finish_books @"finishBooks"
#define TopicHomeRes_psize @"psize"
#define TopicHomeRes_page @"page"
@interface TopicHomeRes : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPsize_:1;
  BOOL hasPage_:1;
  UInt32 psize;
  UInt32 page;
  NSMutableArray * interestBooksArray;
  NSMutableArray * finishBooksArray;
}
- (BOOL) hasPsize;
- (BOOL) hasPage;
@property (readonly, strong) NSArray<Book*> * interestBooks;
@property (readonly, strong) NSArray<Book*> * finishBooks;
@property (readonly) UInt32 psize;
@property (readonly) UInt32 page;
- (Book*)interestBooksAtIndex:(NSUInteger)index;
- (Book*)finishBooksAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TopicHomeResBuilder*) builder;
+ (TopicHomeResBuilder*) builder;
+ (TopicHomeResBuilder*) builderWithPrototype:(TopicHomeRes*) prototype;
- (TopicHomeResBuilder*) toBuilder;

+ (TopicHomeRes*) parseFromData:(NSData*) data;
+ (TopicHomeRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TopicHomeRes*) parseFromInputStream:(NSInputStream*) input;
+ (TopicHomeRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TopicHomeRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TopicHomeRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TopicHomeResBuilder : PBGeneratedMessageBuilder {
@private
  TopicHomeRes* resultTopicHomeRes;
}

- (TopicHomeRes*) defaultInstance;

- (TopicHomeResBuilder*) clear;
- (TopicHomeResBuilder*) clone;

- (TopicHomeRes*) build;
- (TopicHomeRes*) buildPartial;

- (TopicHomeResBuilder*) mergeFrom:(TopicHomeRes*) other;
- (TopicHomeResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TopicHomeResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray<Book*> *)interestBooks;
- (Book*)interestBooksAtIndex:(NSUInteger)index;
- (TopicHomeResBuilder *)addInterestBooks:(Book*)value;
- (TopicHomeResBuilder *)setInterestBooksArray:(NSArray<Book*> *)array;
- (TopicHomeResBuilder *)clearInterestBooks;

- (NSMutableArray<Book*> *)finishBooks;
- (Book*)finishBooksAtIndex:(NSUInteger)index;
- (TopicHomeResBuilder *)addFinishBooks:(Book*)value;
- (TopicHomeResBuilder *)setFinishBooksArray:(NSArray<Book*> *)array;
- (TopicHomeResBuilder *)clearFinishBooks;

- (BOOL) hasPsize;
- (UInt32) psize;
- (TopicHomeResBuilder*) setPsize:(UInt32) value;
- (TopicHomeResBuilder*) clearPsize;

- (BOOL) hasPage;
- (UInt32) page;
- (TopicHomeResBuilder*) setPage:(UInt32) value;
- (TopicHomeResBuilder*) clearPage;
@end

#define TopicChart_id @"id"
#define TopicChart_name @"name"
#define TopicChart_abstract @"abstract"
#define TopicChart_conver_url @"converUrl"
#define TopicChart_books_num @"booksNum"
#define TopicChart_view_num @"viewNum"
@interface TopicChart : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasName_:1;
  BOOL hasAbstract_:1;
  BOOL hasConverUrl_:1;
  BOOL hasId_:1;
  BOOL hasBooksNum_:1;
  BOOL hasViewNum_:1;
  NSString* name;
  NSString* abstract;
  NSString* converUrl;
  UInt32 id;
  UInt32 booksNum;
  UInt32 viewNum;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasAbstract;
- (BOOL) hasConverUrl;
- (BOOL) hasBooksNum;
- (BOOL) hasViewNum;
@property (readonly) UInt32 id;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* abstract;
@property (readonly, strong) NSString* converUrl;
@property (readonly) UInt32 booksNum;
@property (readonly) UInt32 viewNum;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TopicChartBuilder*) builder;
+ (TopicChartBuilder*) builder;
+ (TopicChartBuilder*) builderWithPrototype:(TopicChart*) prototype;
- (TopicChartBuilder*) toBuilder;

+ (TopicChart*) parseFromData:(NSData*) data;
+ (TopicChart*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TopicChart*) parseFromInputStream:(NSInputStream*) input;
+ (TopicChart*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TopicChart*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TopicChart*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TopicChartBuilder : PBGeneratedMessageBuilder {
@private
  TopicChart* resultTopicChart;
}

- (TopicChart*) defaultInstance;

- (TopicChartBuilder*) clear;
- (TopicChartBuilder*) clone;

- (TopicChart*) build;
- (TopicChart*) buildPartial;

- (TopicChartBuilder*) mergeFrom:(TopicChart*) other;
- (TopicChartBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TopicChartBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (UInt32) id;
- (TopicChartBuilder*) setId:(UInt32) value;
- (TopicChartBuilder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (TopicChartBuilder*) setName:(NSString*) value;
- (TopicChartBuilder*) clearName;

- (BOOL) hasAbstract;
- (NSString*) abstract;
- (TopicChartBuilder*) setAbstract:(NSString*) value;
- (TopicChartBuilder*) clearAbstract;

- (BOOL) hasConverUrl;
- (NSString*) converUrl;
- (TopicChartBuilder*) setConverUrl:(NSString*) value;
- (TopicChartBuilder*) clearConverUrl;

- (BOOL) hasBooksNum;
- (UInt32) booksNum;
- (TopicChartBuilder*) setBooksNum:(UInt32) value;
- (TopicChartBuilder*) clearBooksNum;

- (BOOL) hasViewNum;
- (UInt32) viewNum;
- (TopicChartBuilder*) setViewNum:(UInt32) value;
- (TopicChartBuilder*) clearViewNum;
@end

#define TopicChartReq_type @"type"
@interface TopicChartReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasType_:1;
  UInt32 type;
}
- (BOOL) hasType;
@property (readonly) UInt32 type;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TopicChartReqBuilder*) builder;
+ (TopicChartReqBuilder*) builder;
+ (TopicChartReqBuilder*) builderWithPrototype:(TopicChartReq*) prototype;
- (TopicChartReqBuilder*) toBuilder;

+ (TopicChartReq*) parseFromData:(NSData*) data;
+ (TopicChartReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TopicChartReq*) parseFromInputStream:(NSInputStream*) input;
+ (TopicChartReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TopicChartReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TopicChartReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TopicChartReqBuilder : PBGeneratedMessageBuilder {
@private
  TopicChartReq* resultTopicChartReq;
}

- (TopicChartReq*) defaultInstance;

- (TopicChartReqBuilder*) clear;
- (TopicChartReqBuilder*) clone;

- (TopicChartReq*) build;
- (TopicChartReq*) buildPartial;

- (TopicChartReqBuilder*) mergeFrom:(TopicChartReq*) other;
- (TopicChartReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TopicChartReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (UInt32) type;
- (TopicChartReqBuilder*) setType:(UInt32) value;
- (TopicChartReqBuilder*) clearType;
@end

#define TopicChartRes_tcs @"tcs"
@interface TopicChartRes : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * tcsArray;
}
@property (readonly, strong) NSArray<TopicChart*> * tcs;
- (TopicChart*)tcsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TopicChartResBuilder*) builder;
+ (TopicChartResBuilder*) builder;
+ (TopicChartResBuilder*) builderWithPrototype:(TopicChartRes*) prototype;
- (TopicChartResBuilder*) toBuilder;

+ (TopicChartRes*) parseFromData:(NSData*) data;
+ (TopicChartRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TopicChartRes*) parseFromInputStream:(NSInputStream*) input;
+ (TopicChartRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TopicChartRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TopicChartRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TopicChartResBuilder : PBGeneratedMessageBuilder {
@private
  TopicChartRes* resultTopicChartRes;
}

- (TopicChartRes*) defaultInstance;

- (TopicChartResBuilder*) clear;
- (TopicChartResBuilder*) clone;

- (TopicChartRes*) build;
- (TopicChartRes*) buildPartial;

- (TopicChartResBuilder*) mergeFrom:(TopicChartRes*) other;
- (TopicChartResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TopicChartResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray<TopicChart*> *)tcs;
- (TopicChart*)tcsAtIndex:(NSUInteger)index;
- (TopicChartResBuilder *)addTcs:(TopicChart*)value;
- (TopicChartResBuilder *)setTcsArray:(NSArray<TopicChart*> *)array;
- (TopicChartResBuilder *)clearTcs;
@end

#define TopicChartBookReq_tcid @"tcid"
@interface TopicChartBookReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTcid_:1;
  UInt32 tcid;
}
- (BOOL) hasTcid;
@property (readonly) UInt32 tcid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TopicChartBookReqBuilder*) builder;
+ (TopicChartBookReqBuilder*) builder;
+ (TopicChartBookReqBuilder*) builderWithPrototype:(TopicChartBookReq*) prototype;
- (TopicChartBookReqBuilder*) toBuilder;

+ (TopicChartBookReq*) parseFromData:(NSData*) data;
+ (TopicChartBookReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TopicChartBookReq*) parseFromInputStream:(NSInputStream*) input;
+ (TopicChartBookReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TopicChartBookReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TopicChartBookReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TopicChartBookReqBuilder : PBGeneratedMessageBuilder {
@private
  TopicChartBookReq* resultTopicChartBookReq;
}

- (TopicChartBookReq*) defaultInstance;

- (TopicChartBookReqBuilder*) clear;
- (TopicChartBookReqBuilder*) clone;

- (TopicChartBookReq*) build;
- (TopicChartBookReq*) buildPartial;

- (TopicChartBookReqBuilder*) mergeFrom:(TopicChartBookReq*) other;
- (TopicChartBookReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TopicChartBookReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTcid;
- (UInt32) tcid;
- (TopicChartBookReqBuilder*) setTcid:(UInt32) value;
- (TopicChartBookReqBuilder*) clearTcid;
@end

#define TopicChartBookRes_books @"books"
@interface TopicChartBookRes : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * booksArray;
}
@property (readonly, strong) NSArray<Book*> * books;
- (Book*)booksAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TopicChartBookResBuilder*) builder;
+ (TopicChartBookResBuilder*) builder;
+ (TopicChartBookResBuilder*) builderWithPrototype:(TopicChartBookRes*) prototype;
- (TopicChartBookResBuilder*) toBuilder;

+ (TopicChartBookRes*) parseFromData:(NSData*) data;
+ (TopicChartBookRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TopicChartBookRes*) parseFromInputStream:(NSInputStream*) input;
+ (TopicChartBookRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TopicChartBookRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TopicChartBookRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TopicChartBookResBuilder : PBGeneratedMessageBuilder {
@private
  TopicChartBookRes* resultTopicChartBookRes;
}

- (TopicChartBookRes*) defaultInstance;

- (TopicChartBookResBuilder*) clear;
- (TopicChartBookResBuilder*) clone;

- (TopicChartBookRes*) build;
- (TopicChartBookRes*) buildPartial;

- (TopicChartBookResBuilder*) mergeFrom:(TopicChartBookRes*) other;
- (TopicChartBookResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TopicChartBookResBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray<Book*> *)books;
- (Book*)booksAtIndex:(NSUInteger)index;
- (TopicChartBookResBuilder *)addBooks:(Book*)value;
- (TopicChartBookResBuilder *)setBooksArray:(NSArray<Book*> *)array;
- (TopicChartBookResBuilder *)clearBooks;
@end


// @@protoc_insertion_point(global_scope)
